output_dir: ~/experiments/
checkpoint: /home/hodgesf/experiments/KnowledgeGraphCompletion/RDKG/NBFNet/2026-05-25-15-04-21/model_epoch_1.pth 
fast_test: 1000

dataset:
  class: RDKG
  path: /home/hodgesf/Desktop/code/cclb/splits

task:
  class: KnowledgeGraphCompletion
  model:
    class: NBFNet
    input_dim: 16
    hidden_dims: [16, 16, 16, 16, 16, 16]
    message_func: distmult
    aggregate_func: sum
    short_cut: yes
    layer_norm: yes
    dependent: no
  criterion: bce
  num_negative: 32
  strict_negative: yes
  adversarial_temperature: 1
  sample_weight: no
  full_batch_eval: yes

optimizer:
  class: Adam
  lr: 5.0e-3

engine:
  gpus: {{ gpus }}
  batch_size: 4

train:
  num_epoch: 3

metric: mrr