output_dir: ~/experiments/
fast_test: 1000

dataset:
  class: RDKG
  path: /nfs/stak/users/hodgesf/data/splits_human

task:
  class: KnowledgeGraphCompletion
  model:
    class: MaskedNBFNet
    selector_dim: 32
    lambda_l1: 1.0e-8        # changed from 1e-7
    audit: yes
    input_dim: 32
    hidden_dims: [32,32,32,32,32,32]
    message_func: distmult
    aggregate_func: sum
    short_cut: yes
    layer_norm: yes
    dependent: no
  criterion: bce
  num_negative: 32
  strict_negative: yes
  adversarial_temperature: 1
  sample_weight: no
  full_batch_eval: yes

optimizer:
  class: Adam
  lr: 5.0e-4

engine:
  gpus: {{ gpus }}
  batch_size: 4            # bs=2 instead of 4 to fit on H100 80GB with margin
  log_interval: 10         # short run, more frequent logging

train:
  num_epoch: 4
  batch_per_epoch: 500     # 200 batches = ~1 hour quick probe

metric: mrr
